<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>An opinionated C# Toolkit targeting Azure OpenAI for Microsoft Agent Framework that makes life eaisier</Description>
	</PropertyGroup>

	<Import Project="..\..\nuget-package.props" />

	<ItemGroup>
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AgentFrameworkToolkit.OpenAI\AgentFrameworkToolkit.OpenAI.csproj" />
	</ItemGroup>
  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
