<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>An opinionated C# Toolkit for Microsoft Agent Framework that makes life easier</Description>
	</PropertyGroup>

	<Import Project="..\..\nuget-package.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI" />
		<PackageReference Include="JetBrains.Annotations" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>AgentFrameworkToolkit.Jev</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>AgentFrameworkToolkit.Anthropic</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>AgentFrameworkToolkit.AzureOpenAI</_Parameter1>
		</AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>AgentFrameworkToolkit.OpenAI</_Parameter1>
    </AssemblyAttribute>
	</ItemGroup>
	<ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\AgentFrameworkToolkit.Tools\AgentFrameworkToolkit.Tools.csproj" />
	</ItemGroup>
</Project>
