<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>An opinionated C# Toolkit targeting Anthropic for Microsoft Agent Framework that makes life eaisier</Description>
	</PropertyGroup>

	<Import Project="..\..\nuget-package.props" />

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI.Anthropic" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AgentFrameworkToolkit\AgentFrameworkToolkit.csproj" />
	</ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
